flysystem:
    storages:
        screenshots.storage:
            adapter: 'asyncaws'
            options:
                client: 'AsyncAws\S3\S3Client'
                bucket: '%env(R2_BUCKET)%'
                prefix: ''