<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Alignement du schéma sur DBAL 4 :
 *  - colonnes id SERIAL (séquence + DEFAULT nextval) converties en IDENTITY,
 *    en repartant du max(id) courant pour ne casser aucune insertion ;
 *  - suppression des commentaires de type DC2Type devenus inutiles.
 */
final class Version20260919000000 extends AbstractMigration
{
    private const TABLES = [
        '"user"',
        'central_bank',
        'chat_message',
        'confluence',
        'daily_news',
        'messenger_messages',
        'timeframe',
        'trade',
        'trade_error',
        'trade_screenshot',
        'trade_type',
        'trend',
    ];

    private const COMMENTS_TO_DROP = [
        ['"user"', 'created_at'],
        ['central_bank', 'updated_at'],
        ['chat_message', 'created_at'],
        ['chat_message', 'read_at'],
        ['daily_news', 'date'],
        ['daily_news', 'generated_at'],
        ['messenger_messages', 'available_at'],
        ['messenger_messages', 'created_at'],
        ['messenger_messages', 'delivered_at'],
        ['trade_screenshot', 'created_at'],
    ];

    public function getDescription(): string
    {
        return 'DBAL 4: convert SERIAL ids to IDENTITY (preserving counters) and drop legacy DC2Type comments';
    }

    public function up(Schema $schema): void
    {
        foreach (self::TABLES as $table) {
            $bare = trim($table, '"');
            $seq = sprintf('%s_id_seq', $bare);

            // SERIAL → IDENTITY : détacher puis supprimer l'ancienne séquence,
            // ajouter l'identité, et caler son compteur sur max(id)+1
            $this->addSql(sprintf('ALTER TABLE %s ALTER id DROP DEFAULT', $table));
            $this->addSql(sprintf('ALTER SEQUENCE IF EXISTS %s OWNED BY NONE', $seq));
            $this->addSql(sprintf('DROP SEQUENCE IF EXISTS %s', $seq));
            $this->addSql(sprintf('ALTER TABLE %s ALTER id ADD GENERATED BY DEFAULT AS IDENTITY', $table));
            $this->addSql(sprintf(
                "SELECT setval(pg_get_serial_sequence('%s', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM %s), false)",
                str_replace('"', '', $table) === 'user' ? '"user"' : $table,
                $table
            ));
        }

        foreach (self::COMMENTS_TO_DROP as [$table, $column]) {
            $this->addSql(sprintf('COMMENT ON COLUMN %s.%s IS NULL', $table, $column));
        }
    }

    public function down(Schema $schema): void
    {
        // Retour au style SERIAL (équivalent fonctionnel) ; les commentaires
        // DC2Type ne sont pas restaurés (DBAL 3 sait les recréer si besoin).
        foreach (self::TABLES as $table) {
            $bare = trim($table, '"');
            $seq = sprintf('%s_id_seq', $bare);

            $this->addSql(sprintf('ALTER TABLE %s ALTER id DROP IDENTITY IF EXISTS', $table));
            $this->addSql(sprintf('CREATE SEQUENCE %s OWNED BY %s.id', $seq, $table));
            $this->addSql(sprintf("SELECT setval('%s', (SELECT COALESCE(MAX(id), 0) + 1 FROM %s), false)", $seq, $table));
            $this->addSql(sprintf("ALTER TABLE %s ALTER id SET DEFAULT nextval('%s')", $table, $seq));
        }
    }
}
