<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930143401 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Table central_bank_refresh : état et compte rendu des actualisations de taux par l\'IA (app:cycles:refresh)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE central_bank_refresh (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(10) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, changes JSON NOT NULL, message TEXT DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE central_bank_refresh');
    }
}
